### ISSUE TITLE
UART mode limited to 20 characters

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Bluefruit_LE_Connect_v2#61] opened 2024-01-17 14:33 UTC
I am only able to send up to 20 characters via the UART Mode with the IOS(v3.7.0) and MaCOS (v3.6.2) Desktop app.
With the older version of the MacOS desktop app (version 2.2.2) This limit did not apply. I can send longer messages.

If a  message longer than 20 characters is entered, it is echoed but it does not appear to be sent.
No errors are reported.

Is the 20 character limit known and intended?

**Comment by dhalbert** [comment] 2024-01-17 15:46
Confirmed this is an issue. Tested iOS app version 3.7.0 on iOS 17.2.1 with https://github.com/adafruit/Adafruit_CircuitPython_BLE/blob/main/examples/ble_uart_echo_test.py on a Feather nRF52840 running CircuitPython 8.2.9 and also CircuitPython 7.3.3.

**Comment by antonio-openroad** [comment] 2024-02-20 18:44
There is no character limit in the app. If the message to be sent is longer than the MTU (Maximum Transfer Unit) negotiated during the BLE connection, the app will slip the text into multiple messages and send them sequentially.

I tested the iOS and macOS versions (3.7.0) and was able to send more than 20 characters. 
I used a Bluefruit LE Friend connected to a computer and CoolTerm to check the data received by UART. 

<img width="1687" alt="Screenshot 2024-02-20 at 19 17 09" src="https://github.com/adafruit/Bluefruit_LE_Connect_v2/assets/3625420/b59d498b-141a-4f9f-932b-1c5cd51e0052">

So perhaps there could be a problem with the libraries used in CircuitPython?

Adding some more information, 20 bytes was the default MTU for BLE connections for many years. Modern devices usually negotiate a bigger MTU (around 512 bytes) but is not unusual for it to set it to 20 bytes. 
So my guess is that the text is split in multiple messages, but the CircuitPython library is only processing the first one (which is 20 bytes long).

**Comment by dhalbert** [comment] 2024-10-17 03:29
This issue is really due to the default `max_length` being 20 for characteristics in the `adafruit_ble` library. But a BLE client using NUS (Nordic UART Service) normally expects the maximum writable length to be the MTU size - 3. That includes the Bluefruit LE Connect apps. So it is a library issue. I'm closing as a dupe, in favor of https://github.com/adafruit/Adafruit_CircuitPython_BLE/issues/94.

**Closed by dhalbert** 2024-10-17 03:29 UTC
